format = """
[î‚¶](#FFA500)\
[$env_var$username$hostname](fg:#1B2430 bg:#FFA500)\
[î‚°](bg:#1572A1 fg:#FFA500)\
$directory\
[î‚°](fg:#1572A1 bg:#F5B17B)\
$git_branch\
$git_status\
[î‚°](fg:#F5B17B bg:#798777)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$dotnet\
[î‚°](fg:#798777 bg:#0078d4)\
$azure\
${env_var.AZURE_USERTYPE}\
[î‚°](fg:#0078d4 bg:#2F8F9D)\
$kubernetes\
[î‚°](fg:#2F8F9D bg:#33658A)\
$time\
[î‚° ](fg:#33658A)\
$cmd_duration\
\n$character\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
format = '$user'

[hostname]
ssh_only = false
format = "@$hostname "
disabled = false

[env_var]
disabled = true
format = '$env_value/'
variable = "INSTANCE_NAME"
default = "-"

[directory]
style = "bg:#1572A1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"
truncate_to_repo = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[c]
symbol = "î˜ "
style = "bg:#798777"
format = '[[ $symbol ($version) ](bg:#798777)]($style)'

[elixir]
symbol = "î‰µ "
style = "bg:#798777"
format = '[[ $symbol ($version) ](bg:#798777)]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#798777"
format = '[[ $symbol ($version) ](bg:#798777)]($style)'

[git_branch]
symbol = "ï˜"
style = "bg:#F5B17B"
format = '[[ $symbol $branch ](fg:#52524E bg:#F5B17B)]($style)'

[git_status]
style = "bg:#F5B17B"
format = '[[($all_status$ahead_behind )](fg:#52524E bg:#F5B17B)]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#798777"
format = '[[ $symbol ($version) ](bg:#798777)]($style)'

[haskell]
symbol = "î· "
style = "bg:#798777"
format = '[[ $symbol ($version) ](bg:#798777)]($style)'

[java]
symbol = "î‰– "
style = "bg:#798777"
format = '[[ $symbol ($version) ](bg:#798777)]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#798777"
format = '[[ $symbol ($version) ](bg:#798777)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#798777"
format = '[[ $symbol ($version) ](bg:#798777)]($style)'

[nim]
symbol = "ğŸ‘‘"
style = "bg:#798777"
format = '[[ $symbol ($version) ](bg:#798777)]($style)'

[rust]
symbol = "ğŸ¦€"
style = "bg:#798777"
format = '[[ $symbol ($version) ](bg:#798777)]($style)'

[dotnet]
symbol = "ğŸ¥…"
style = "bg:#798777"
format = '[[ $symbol ($version) ](bg:#798777)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[[ â™¥ $time ](bg:#33658A)]($style)'

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[kubernetes]
style = "bg:#2F8F9D"
format = '[â›µ $context \($namespace\)]($style)'
disabled = false

[kubernetes.context_aliases]
# "(?P<user>^([\\w-]+@([\\w-]+\\.)+[\\w-]{2,4}))@(?P<cluster>([\\w-]+)).*" = "$cluster"
"(?P<arn>^([\\w\\-:]+))/(?P<cluster>([\\w-]+))" = "$cluster"
# "dev.local.cluster.k8s" = "dev"
# ".*/openshift-cluster/.*" = "openshift"
# "gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"

[docker_context]
symbol = "ïŒˆ "
style = "bg:#2F8F9D"
format = '[[ $symbol $context ](bg:#2F8F9D)]($style) $path'

[azure]
disabled = false
#format = "on [$symbol($username)]($style) "
#format = "[$symbol($username)]($style)"
format = "[$symbol($subscription)]($style)"
symbol = "ó° … "
#style = "blue bold"
style = "bg:#0078d4"

[azure.subscription_aliases]
very-long-subscription-name = 'vlsn'

[env_var.AZURE_USERTYPE]
disabled = false
variable = "AZURE_USERTYPE"
format = "[/$symbol($env_value)]($style)"
style = "bg:#0078d4"
